services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  backend:
    image: ghcr.io/camille-girard/backend
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "SCRIPT_FILENAME=/app/public/index.php REQUEST_METHOD=GET REQUEST_URI=/api/health cgi-fcgi -bind -connect localhost:9000 | grep 'running.*true' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  frontend:
    image: ghcr.io/camille-girard/frontend

  nginx:
    image: ghcr.io/camille-girard/nginx
    ports:
      - '80:80'
    depends_on:
      - backend
      - frontend
