services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '8080:80'
    depends_on:
      - db

  backend:
    build:
      context: backend
      dockerfile: docker/Dockerfile
      target: dev
      args:
        PHP_VERSION: 8.4.1
    volumes:
      - ./backend:/app
    ports:
      - '8000:8080'
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - backend
