services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '8080:80'
    depends_on:
      - db

  backend:
    build:
      context: backend
      dockerfile: docker/Dockerfile
      target: dev
      args:
        PHP_VERSION: 8.4.1
    volumes:
      - ./backend:/app
      - ./backend:/var/www/html
    ports:
      - '8000:8080'
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "SCRIPT_FILENAME=/app/public/index.php REQUEST_METHOD=GET REQUEST_URI=/api/health cgi-fcgi -bind -connect localhost:9000 | grep 'running.*true' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NITRO_PRESET: node


  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - '8085:80'
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - backend
      - frontend
