services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'

  backend:
    image: ghcr.io/camille-girard/backend
    depends_on:
      - db

  frontend:
    image: ghcr.io/camille-girard/frontend

  nginx:
    image: ghcr.io/camille-girard/nginx
    depends_on:
      - backend
