export enum AccommodationAdvantage {
    BREAKFAST = 'breakfast',
    SNACK = 'snack',
    GARDEN = 'garden',
    GAME_ROOM = 'game_room',
    TERRACE = 'terrace',
    BALCONY = 'balcony',
    BARBECUE = 'barbecue',
    CASTLE_ACCESS = 'castle_access',
    CASTLE_VISIT = 'castle_visit',
    WIFI = 'wifi',
    PARKING = 'parking',
    POOL = 'pool',
    SPA = 'spa',
    GYM = 'gym',
    KITCHEN = 'kitchen',
    LAUNDRY = 'laundry',
    AIR_CONDITIONING = 'air_conditioning',
    HEATING = 'heating',
    TV = 'tv',
    COMMON_ROOM_ACCESS = 'common_room_access',
}

export const accommodationAdvantageLabels: Record<AccommodationAdvantage, string> = {
    [AccommodationAdvantage.BREAKFAST]: 'Petit-déjeuner offert',
    [AccommodationAdvantage.SNACK]: 'Goûter',
    [AccommodationAdvantage.GARDEN]: 'Jardin',
    [AccommodationAdvantage.GAME_ROOM]: 'Salle de jeux',
    [AccommodationAdvantage.TERRACE]: 'Terrasse',
    [AccommodationAdvantage.BALCONY]: 'Balcon',
    [AccommodationAdvantage.BARBECUE]: 'Barbecue',
    [AccommodationAdvantage.CASTLE_ACCESS]: 'Accès au château',
    [AccommodationAdvantage.CASTLE_VISIT]: 'Visite du château',
    [AccommodationAdvantage.WIFI]: 'Wi-Fi gratuit',
    [AccommodationAdvantage.PARKING]: 'Parking',
    [AccommodationAdvantage.POOL]: 'Piscine',
    [AccommodationAdvantage.SPA]: 'Spa',
    [AccommodationAdvantage.GYM]: 'Salle de sport',
    [AccommodationAdvantage.KITCHEN]: 'Cuisine équipée',
    [AccommodationAdvantage.LAUNDRY]: 'Lave-linge',
    [AccommodationAdvantage.AIR_CONDITIONING]: 'Climatisation',
    [AccommodationAdvantage.HEATING]: 'Chauffage',
    [AccommodationAdvantage.TV]: 'Télévision',
    [AccommodationAdvantage.COMMON_ROOM_ACCESS]: 'Accès à la salle commune',
};
